services:
  # The Go service powering API.
  backend:
    image: fireflyzero/backend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      API_POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 0.0.0.0:${API_PORT}:${API_PORT}
    depends_on:
      postgres:
        condition: service_healthy
